# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b17fca3fcd67baddeb6c8da953cf7a167f134b501da100951cd241b62f53141f58ce5d683408cd1c735e19da16417e4867c1300f891022a70a0cb64af4a6a6bc

test:
  secret_key_base: 77e5529ead3dc323525bca594a8eaf5d6bd5d6fa0b4b26af6e0c6e547c477598989b63e1ba09c1c1e533842e930c1626669777e439968d7e0b9b96aaf728fa78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
